import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useQuery } from "@apollo/client";
import { TASKS_QUERY, TasksData } from "../graphql/tasks.query";

interface TasksListProps {}

const Home: NextPage<TasksListProps> = () => {
  const { loading, error, data } = useQuery<TasksData>(TASKS_QUERY);

  if (loading) return <p>Loading ...</p>;
  if (error) return <p>Error:{JSON.stringify(error)}</p>;

  const { tasks }: any = data;
  console.log(data);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <ul>
          {tasks.map((task: any, index: any) => {
            return <li key={task.id}>{task.title}</li>;
          })}
        </ul>
      </main>
    </div>
  );
};

export default Home;
